import {  Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import NavContaxt from "@/contaxt/NavContaxt";

 

export const metadata = {
  title: "  Music New App",
  description: "Generated by create next app",
};
 

export default function RootLayout({ children }) {
  return (
    <NavContaxt>
    <html lang="en">
      <body className={`scrollbar-thin scrollbar-thumb-accent scrollbar-track-accent-hover  bodyFont  overflow-x-hidden relative `}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
     </NavContaxt>
  );
}
